name: Create Release

on:
  push:
    branches: [ main ]
    paths:
      - 'memory/**'
      - 'scripts/**'
      - 'templates/**'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Run release script
      run: |
        bash .github/workflows/scripts/generate-release.sh --version-bump patch --package --notes --github-release --pyproject-update
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
